import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ParticlesWrapper } from "@/components/ParticlesWrapper"; // Make sure this path is correct
import TanStackProvider from "@/Providers/TanStackProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black overflow-x-hidden text-white`}
      >
        <ParticlesWrapper
          className="absolute inset-0 -z-10"
          quantity={100}
          staticity={50}
          ease={50}
          color="#FFFFFF"
        >
          <TanStackProvider>{children}</TanStackProvider>
        </ParticlesWrapper>
      </body>
    </html>
  );
}
